feat: Implement StepParameter for fixed-interval optimization
freqtrade/freqtrade pull request #10970
Opened 2024-11-22 12:31 UTC by TekpreXyz

Adds new class extending NumericParameter to support:
- Parametric values with fixed steps between min and max
- Automatic validation of steps and default values
- Full compatibility with hyperopt optimization framework
- Proper parameter space generation for scikit-optimize

## Summary

Solve the issue: #___

## Quick changelog

- <change log 1>
- <change log 1>

## What's new?

2024-11-24 12:29 UTC, xmatthias requested changes
well leaving styling problems aside (read the contributing guide ;) ) - i don't think this does what you think.

`.step` is never used after assignment (aside from `__repr__()`) - so while it suggests "you'll get every 10th number" - that's not actually happening.

For such a particular feature, we'll also want a test that ensures that the functionality works correctly (tests for `DecimalParameter` might proof to be a good template).

2024-12-03 01:28 UTC, stash86 commented
Personally, I don't see why we need such parameter when we can do so using IntParameter already with some minor codes, like `(5 * self.int_step.value)` if you want to have `5, 10, 15,etc`. You don't have to worry about the range have to be divisable by the step number.

You can do so using DecimalParameter as well.

2025-02-11 06:56 UTC, xmatthias commented
Closing this as it 
* artificially limits how this can be done - i can't do "from 1 to 10, step 3" (expecting 1, 4, 7, 10 as output) - as 1 is not divisible by 3).
* doesn't do what it claims
* there's simpler approaches via `IntParameter` and custom multipliers - providing the above flexibility.

2025-02-11 06:56 UTC, closed without merging

2026-06-30 08:04 UTC, viotemp1 commented
It was just to pass the step further to optuna, nothing more. There are alternative ways to do it (which I did)....