allow json in environment variables
freqtrade/freqtrade pull request #10979
Opened 2024-11-24 13:34 UTC by amalysh

## Summary
Allow setting json in the environment vairables

## What's new?
For example you can set producers from environment and many more like ccxt options etc.

FREQTRADE__EXTERNAL_MESSAGE_CONSUMER__PRODUCERS:  [{"name": "default", "host": "xxx", "port": 4711, "secure": true, "ws_token": "xxx"}]

This is useful if for example you try to run freqtrade on PaaS like dokku/heroku and use variable storage of that platform in order to not expose config with secrets.

2024-11-25 06:02 UTC, xmatthias requested changes
I don't see the usecase for options that are not arrays if i'm honest (you can set every ccxt option i've ever had to set via regular environment variables) - and allowing the parsing of plain json for everything seems a bit excessive.

Personally, i'd much rather prefer something more pointed, like  `FREQTRADE__EXTERNAL_MESSAGE_CONSUMER__PRODUCERS[0]__WS_TOKEN` - but i don't think that's supported ATM, and the effort for this is probably not worth it.

As the only usecase i can see for this is arrays (actually, only this array if i'm honest), i think this should be limited to this - like - the parsed result must be an array to be acceptable input? 

We'll also want a test for this for sure.

2024-11-25 11:26 UTC, amalysh commented
Hi,
there could be even more cases, where json would be great to have inside. Next example that I had myself, was settings of ccxt options, which are camelcase.

Example from me:
FREQTRADE__EXCHANGE__CCXT_CONFIG__OPTIONS:        {"sandboxMode": true}

And there was a ticket, where this change will help to solve: https://github.com/freqtrade/freqtrade/issues/10481

If you agree to accept such change I will provide tests for it.

2024-11-25 11:29 UTC, xmatthias commented
I actually don't.

Yes, this was asked - but setting a setting like this via Environment variable makes no sense (leaving aside the fact that sandbox mode shouldn't be set at all as these markets won't have ANY volume).
It's not sensitive - so you can easily set it in the config directly.

Let's limit this to arrays only - though even there, I'd personally prefer a different solution - but the effort for that will definitely not be worth it.

2024-11-25 11:35 UTC, amalysh commented
I don't see why limiting to array only if you can have all possibilities with simple json one liner? let user decide, which config he has to set and how. I just see that as waste of time to just implement a array instead of simple allowing json and have all possibilities, which will allow user to decide how to use it.

2024-11-25 13:23 UTC, xmatthias commented
Let me put it that way: 
it's not about the functionality per se (though I'm not sure if `json.loads` is 100% safe for user-provided inputs) - but about the willingness to support such functionality going forward.

Trying to "fizzle" an object into a valid array can be a challenge, one that we'll have to support users in if they fail to do so.
Enlarging this to supporting users with "you can essentially provide the whole config in a string via environment variable" is not something I'm willing to waste my time on.
Also, the bigger the scope, the bigger the impact should we decide to remove this again (see proper solution to this below).

I'm not happy supporting arrays in this way really, either, but don't see a feasible alternative.
As said above, I would prefer a `FREQTRADE__EXTERNAL_MESSAGE_CONSUMER__PRODUCERS[0]__WS_TOKEN` approach - but don't see this as feasible - not for what it tries to accomplish.

Limiting to array is a compromise I'm willing to take - if that's not working for you, then please take this as a "reject" for this PR, as i don't intend to support people trying to inject half of their config via environment variable.

Thanks for your understanding.

2024-12-08 07:37 UTC, xmatthias approved these changes
Added the necessary limitation to lists to this PR and added a few tests for this.

With that - LGTM :+1:

2024-12-08 07:55 UTC, merged

2024-12-09 08:45 UTC, amalysh commented
@xmatthias Thanks for this change!