fix(trade): reversing an open trade doesn't work
freqtrade/freqtrade pull request #11114
Opened 2024-12-20 14:06 UTC by koistya

## Summary

![image](https://github.com/user-attachments/assets/58c3bfc0-a171-4d11-8e5c-d466edb06e94)

Solve the issue: #9183 

## Quick changelog

The fix ensures that when both entry and exit signals occur on the same candle, the Freqtrade bot:

1. Tracks Closed Trades: Updates the `exit_positions` method to return a list of trades that were successfully closed during the current cycle.
2. Handles Reverse Entries Immediately: Modifies the process method to process entry signals for pairs with closed trades within the same cycle, allowing reverse positions to be opened right after closing the previous trade.
3. Preserves Reentry Logic: Ensures the `create_trade` method works without unnecessary locks, allowing reentries when valid reverse signals exist.

This fix seamlessly integrates reverse position handling into the bot’s trading cycle without disrupting its normal operations.

## What's new?

2024-12-20 15:46 UTC, xmatthias commented
Please provide logs and proof that this is actually happening (as mentioned in the issue).
this looks like a hot-shot "i'll fix this" implementation without actually understanding the problem - or having any proof that there **is** a problem - and not just a misconfiguration on your part (which is my assumption at this moment).

At first glance, your change would open an exit order without any check if the previous exit actually filled - so it's introducing a bug  - not fixing anything.


So - before spending any minute on this - please provide logs, configuration, and best a full reproduction strategy where you can show that the reversal is NOT taking place.
Without that - there's no point in looking at the changes - as i don't think there's anything to change.

2024-12-20 17:07 UTC, xmatthias requested changes
After looking at the code i can say ... 
this introduces a couple of bugs - and seems to work around a bug in your strategy, without taking actual trading logic (orders may not fill immediately) into consideration.

While i'll leave this open for now - to give you time to present logs on what you think happens in develop (which should actually be an issue) - this has about 0 chance to be merged - as the whole logic it tries to introduce is flawed from the ground up.

2024-12-20 17:07 UTC, xmatthias commented on freqtrade/freqtradebot.py
> +                self.create_trade(trade.pair)
This will ignore regular pairlist sequence - so this is introducing a bug / unwanted behavior.

2024-12-20 17:07 UTC, xmatthias commented on freqtrade/freqtradebot.py
> +                    trades_closed.append(trade)
All this condition means is that an exit order was placed
there's a myrad of things that can happen to an order so it doesn't get filled.

There's absolutely no checks for this - so this again, introduces buggy behavior.

2024-12-21 13:08 UTC, xmatthias commented
Doing a bit more testing on this - it's not a problem of freqtrade - and the logic there works perfectly fine.
on a 5 min strategy (designed to explicitly test this) - i get the following trades.
As you can see - the exit / entry is within about a second - each time switching to the other direction.
![image](https://github.com/user-attachments/assets/90042086-8d2d-439a-983a-b635053cc827)


As such - i'll be closing this - as this is not a problem that needs adressing.
If you cannot get to that - then it's a bug in your strategy.
While we can surely help you with that - this is not the right place to analyze your strategy.

As such, please open a new issue, posting your versions, logs, and a (ideally reduced) strategy where you're experiencing this.

2024-12-21 13:08 UTC, closed without merging

2024-12-23 11:32 UTC, rcpislr commented
Hello. I appreciate you for this great job. 
i want to create a strategy like this reversal trades , for a long position if it goes under a specifi percent for ex.  -0.02 , it will reverse the position to short. 
if it is possible can you share this strategy file just to understand the logic please? 
thanks in advance.

2024-12-23 11:33 UTC, rcpislr commented
> Doing a bit more testing on this - it's not a problem of freqtrade - and the logic there works perfectly fine. on a 5 min strategy (designed to explicitly test this) - i get the following trades. As you can see - the exit / entry is within about a second - each time switching to the other direction. ![image](https://private-user-images.githubusercontent.com/5024695/397929163-90042086-8d2d-439a-983a-b635053cc827.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5NTM3MTQsIm5iZiI6MTczNDk1MzQxNCwicGF0aCI6Ii81MDI0Njk1LzM5NzkyOTE2My05MDA0MjA4Ni04ZDJkLTQzOWEtOTgzYS1iNjM1MDUzY2M4MjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMjNUMTEzMDE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDMxN2I5NzkzNTI1NGE2MDQxZTNiYzE5MzU2N2EyMDQ1NWJlNDg4NTgwYWI3YzJhMDJkZjMzMDQ1MGYwNWVkOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.DbLdGnJJu3w8y56s1TJLPEdt4tz9YzfIgiJXY50rAfs)
> 
> As such - i'll be closing this - as this is not a problem that needs adressing. If you cannot get to that - then it's a bug in your strategy. While we can surely help you with that - this is not the right place to analyze your strategy.
> 
> As such, please open a new issue, posting your versions, logs, and a (ideally reduced) strategy where you're experiencing this.

Hello. I appreciate you for this great job.
i want to create a strategy like this reversal trades , for a long position if it goes under a specifi percent for ex. -0.02 , it will reverse the position to short.
if it is possible can you share this strategy file just to understand the logic please?
thanks in advance.

2024-12-23 12:50 UTC, xmatthias commented
Positions won't reverse this way.

it's based on the assumption that on the candle the exit happens (when the exit order fills) - there's an entry signal in the dataframe going in the other direction.

If there's no signal, then there won't be a reversal.
this is in any case, clearly not the right place to discuss this.