Unwanted exchanges error
freqtrade/freqtrade pull request #4614
Opened 2021-03-28 07:31 UTC by mablue

I added an script to check if exchange not supported by freqtrade.

Thank you for sending your pull request. But first, have you included
unit tests, and is your code PEP8 conformant? [More details](https://github.com/freqtrade/freqtrade/blob/develop/CONTRIBUTING.md)

## Summary
Explain in one sentence the goal of this PR

Solve the issue: #___

## Quick changelog

- <change log #1>
- <change log #2>

## What's new?
*Explain in details what this PR solve or improve. You can include visuals.*

2021-03-28 08:18 UTC, xmatthias requested changes

2021-03-28 08:18 UTC, xmatthias commented on freqtrade/freqtradebot.py
> +          logger.error(f'Exchange, {exchange_name} not supported by freqtrade! continue with your own risk!')
If an exchange is REALLY not working (confirmed not working) - then please add it to the `BAD_EXCHANGES` Dict in `freqtrade/exchange/common.py` with the reason for it - which will have the same effect.

2021-03-30 05:46 UTC, xmatthias commented
I think i'll close this for now, as this is 
a) not the right place to add this
b) it seems like coinEx works for you after all (based on comments in other issues).

2021-03-30 05:46 UTC, closed without merging

2021-03-30 08:15 UTC, mablue commented
Yes its works for me some times when the bot is off and i cancele manually an order.and re run freqtrade will go to the loop of order not found!