Added check method, fails because of magic mock i think
freqtrade/freqtrade pull request #5522
Opened 2021-09-02 07:01 UTC by samgermain

## Summary
Adds a method that checks if a method is implemented on the ccxt exchange class

## Quick changelog
Adds this method to exchange class
- throw_exception_if_method_not_on_exchange(self, method_name: str)

Currently the test for this fail, I think this is because of the way that the exchange object is instantiated in the test

```
exchange = get_patched_exchange(mocker, default_conf, id=exchange_name)
```

I don't know how I would write an actual exchange object implementation in order to pass the tests.

-------------------

There is some overlap between this and `funding-fee`. I realized I needed this method in multiple PRs

2021-09-02 09:30 UTC, xmatthias commented on freqtrade/exchange/exchange.py
> +
This already exists as `exchange_has()`, which however does not raise, but returns False.

There's 2 applications for that - either check at startup to verify if a configuration is valid (check if certain special options exist - like `createMarketOrder`) - or to check during runtime and fall back to alternative means. 
Neither of the 2 benefit from having that method "raise" a "failing" exception (on top of the fact that you're risking keyerrors with the approach you're taking).

2021-09-02 09:31 UTC, xmatthias requested changes
In my opinion we have this already as `exchange_has`.

unless you can explain what the benefit of this over `exchange_has` are i think we can close this.

2021-09-02 20:42 UTC, closed without merging

2021-09-03 01:14 UTC, samgermain commented
> In my opinion we have this already as `exchange_has`.
> 
> unless you can explain what the benefit of this over `exchange_has` are i think we can close this.

`exchange_has` isn't working when I use it, i broke it down to

```
binance = ccxt.binance({
    'api_key': "...",
    'secret': "...",
    'options': {
        'defaultType': 'margin'
    },
})
kraken = ccxt.kraken({
    'api_key': "...",
    'secret': "..."
})
endpoint="fetch_funding_history"

pprint(f"endpoint in binance.has: {endpoint in binance.has}")
pprint(f"binance.has[endpoint]: {binance.has[endpoint]}")
pprint(f"endpoint in ftx.has: {endpoint in ftx.has}")
pprint(f"ftx.has[endpoint]: {ftx.has[endpoint]}")
```
and this is happening
```
'endpoint in binance.has: False'
Traceback (most recent call last):
  File "/Users/sam/Documents/dev/trading/freqtrade/../ccxt-scratch/main.py", line 203, in <module>
    pprint(exchange_has("fetch_funding_history"))
  File "/Users/sam/Documents/dev/trading/freqtrade/../ccxt-scratch/main.py", line 194, in exchange_has
    pprint(f"binance.has[endpoint]: {binance.has[endpoint]}")
KeyError: 'fetch_funding_history'
```

When I run `dir(ccxt.binance())` or `dir(ccxt.ftx())`, `fetch_funding_history` is listed in the results of both

2021-09-03 06:02 UTC, xmatthias commented
fetch_funding_history is wrong - the correct naming is `fetchFundingHistory` (it's a dict that points out the available methods (manually maintained, allowing work on a function before releasing it i assume) - NOT a list of methods using dir.

Having a different method to control for that won't change the fact if you're using the wrong name.

2021-09-03 20:04 UTC, samgermain commented
> fetch_funding_history is wrong - the correct naming is `fetchFundingHistory` (it's a dict that points out the available methods (manually maintained, allowing work on a function before releasing it i assume) - NOT a list of methods using dir.
> 
> Having a different method to control for that won't change the fact if you're using the wrong name.

I edited my exchange_has snippet above to use the endpoint `fetchFundingHistory`, and it works using that snippet but I'm still getting an error when running pytest on freqtrade, and when using `pdb`, I still get 

```
(Pdb) self.exchange_has('fetchFundingHistory')
False
(Pdb) 'fetchFundingHistory' in self._api.has
False
```

I think it has to do with `MagicMock`

```
(Pdb) self._api
<MagicMock id='4862689136'>
(Pdb) self
<freqtrade.exchange.binance.Binance object at 0x121e8e9a0>
```

What would be the best way to do this, because Ideally I would like to check that condition as well

2021-09-03 20:06 UTC, xmatthias commented
Just search through tests - there's a few that patch "has" properly (using a PropertyMock, iirc).

2021-09-03 21:32 UTC, samgermain commented
> Just search through tests - there's a few that patch "has" properly (using a PropertyMock, iirc).

Ok, I've almost got it, I'm getting the wrong number of call_counts in `ccxt_exceptionhandlers` (1 when it's asserted as 5)

```
 def ccxt_exceptionhandlers(mocker, default_conf, api_mock, exchange_name,
                               fun, mock_ccxt_fun, retries=API_RETRY_COUNT + 1, **kwargs):
    
        with patch('freqtrade.exchange.common.time.sleep'):
            with pytest.raises(DDosProtection):
                api_mock.__dict__[mock_ccxt_fun] = MagicMock(side_effect=ccxt.DDoSProtection("DDos"))
                exchange = get_patched_exchange(mocker, default_conf, api_mock, id=exchange_name)
                getattr(exchange, fun)(**kwargs)
>           assert api_mock.__dict__[mock_ccxt_fun].call_count == retries
E           AssertionError: assert 1 == 5
E            +  where 1 = <MagicMock id='4864449936'>.call_count

tests/exchange/test_exchange.py:37: AssertionError
```

2021-09-04 06:16 UTC, xmatthias commented
tough to say without the code - let's please move this to the "failing test" lines - so i can look at it for real :laughing: