Auto buy BNB and self._log_responses patch
freqtrade/freqtrade pull request #6059
Opened 2021-12-12 17:37 UTC by NoahGago

Thank you for sending your pull request. But first, have you included
unit tests, and is your code PEP8 conformant? [More details](https://github.com/freqtrade/freqtrade/blob/develop/CONTRIBUTING.md)

## Summary

Explain in one sentence the goal of this PR

1. Automatically buy BNB for trading fees (only in dry run) based on analysis of typical FreqTrade users.
2. Fixed the self._log_responses variable misnomer, I see that in the fully updated version it's been fixed to be self.log_responses, however I believe that changing the instances of its use to self._log_responses more conforms with naming protocols.

+ Potential early stage solution to the issue: #5562 
+ Variable misnomer patch (self._log_responses in exchange.py)

These edits were made to explore the possibility of buying BNB automatically in order to pay the minimum in trading fees. It was only implemented in dry-run mode however. This was done with changes made to the create_order method in exchange.py, changes to config_bittrex.example.json, and changes to config_binance.example.json. Additionally when testing with Travis CI I noticed that there was an inconsistency with the usage of self._log_responses in exhange.py so I changed the instances of its use to self._log_responses as opposed to self.log_responses.

2021-12-12 19:29 UTC, xmatthias requested changes
i think your branch got messed up somehow - as it seems to roll back certain chances we made lately

2021-12-12 19:29 UTC, xmatthias commented on freqtrade/exchange/exchange.py
> +            asyncio.gather(*input_coroutines, return_exceptions=True))
I don't think changes to this (and subsequent) lines are intentional.

Please don't use your own develop branch for pull requests, but use dedicated branches instead.
Using the "main" branch from another repository usually ends up in chaos.

2021-12-12 19:29 UTC, xmatthias commented on config_examples/config_bittrex.example.json
> +        "reduced_fees_strategy": {
this is definitely the wrong file - BNB is irrelevant for bittrex

2021-12-12 19:29 UTC, xmatthias commented on freqtrade/exchange/exchange.py
> +                self._avoid_duplicate_order = False
i think this section is located wrongly for 2 reasons

buying BNB is irrelevant in dry-run ... so if any, then this should be moved 2 lines to the bottom (and dedented by 4 spaces).

That said - i don't think this should be part of `create_order()` at all. 
Assuming a quick timeframe (1m) - we should try to be as quick as possible - another call to buy BNB is definitely the wrong way (and it's also unnecessary. 

I think this should be running "out of band" - at some random (inactivity) times - so basically, it should be a separate function that's called as part of the bot loop (but only acts every X minutes/hours).

2021-12-12 19:29 UTC, xmatthias commented on freqtrade/exchange/exchange.py
> +        self._BNB_max = exchange_config['reduced_fees_strategy']['BNB_maximum']
i'd not use BNB in the names (not for variables, not for config options).
While you're using it on binance where BNB are relevant, others might be using it on different exchanges on different coins.

2022-01-09 16:48 UTC, HaddadJoe commented
Nice suggestion, I'm interested in this feature

@NoahGago are you still working on this? I can pick up where you left and clean that PR if you're not.

2022-01-09 19:00 UTC, NoahGago commented
Nope I am not! You're free to pick up where I left off!

On Sun, Jan 9, 2022 at 11:48 AM Joe Haddad ***@***.***> wrote:

> Nice suggestion, I'm interested in this feature
>
> @NoahGago <https://github.com/NoahGago> are you still working on this? I
> can pick up where you left and clean that PR if you're not.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/freqtrade/freqtrade/pull/6059#issuecomment-1008334179>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJAIEMAS4ZEC72KGW6B6G5TUVG34ZANCNFSM5J4PR2TA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-01-10 18:41 UTC, xataxxx commented
Totally agree that this should be exchange-agnostic - on KuCoin one might want to buy KCS, on FTX exchange you would want to buy FTT etc.

Besides running at Xh intervall maybe consider running at startup + at the end of SELL order finishing.
Basically re-check at startup + after each sell order closing check if we have enough fee coin left and buy more if needed.

Idea for future (way overkill for first implementation):
Would be awesome if we could calculate and check the full dataframe for the <exchange-coin>/<stake-currency> before buying so that the strategy could advise the bot if the BNB/KCS/FTT pair is having a bad moment and maybe skip buying if some indicators indicate that the price is very high temporarily etc. Then you could also "optimise" the buying of your fee currency when the BNB/KCS/FTT etc is currently selling relatively low.

2022-03-24 07:03 UTC, xmatthias commented
Going to close this as it's abandoned, and there's still too much missing for this to be used as reasonable base.

2022-03-24 07:03 UTC, closed without merging