Added liquidation_buffer to freqtradebot
freqtrade/freqtrade pull request #6386
Opened 2022-02-10 16:15 UTC by samgermain

Cuts the liquidation price short by a default of 5% that can be adjusted in the users config, to help prevent liquidation and liquidation fees to the user

2022-02-10 18:05 UTC, xmatthias commented on freqtrade/freqtradebot.py
> +        self.liquidation_buffer = float(self.config.get('liquidation_buffer', '0.05'))
can you please also add this to the documentation?

also - if you specify the schema in `constants.py` (as number) - you'll not need to parse it explicitly as float (assuming the fallback is also a float, obviously).

This way (without schema) we risk it failing "mid-buy" - if it can't be parsed to a float.

I also don't see a need to do this "on init" (basically assigning it to the freqtrade object) - but we can do the config lookup while executing the trade.

2022-02-10 18:05 UTC, xmatthias commented on freqtrade/freqtradebot.py
> +                isolated_liq + liquidation_buffer
I think the calculation should be separated into a separate function (not in `freqtradebot.py`). 
We'll need it in backtesting as well ... so i'd maybe place it in the exchange class

2022-02-11 05:59 UTC, xmatthias requested changes
Please add the validation to the json schema in `constants.py`.

Also - i would ask you to please read the comments i add to reviews. 
It's honestly very tiring and frustrating to ask for changes - have changes implemented, and then have to ask for the **same exact thing** again.
I'm mentioning this as this is happening quite frequently in your PR's - which is wasting a lot of time (both your's and mine) and could easily be avoided.

2022-02-11 05:59 UTC, xmatthias commented on docs/leverage.md
> +Currently Freqtrade is able to calculate liquidation prices, but does not calculate liquidation fees. Setting your `liquidation_buffer` to 0.0, or using a low `liquidation_buffer` could result in you
```suggestion
Currently Freqtrade is able to calculate liquidation prices, but does not calculate liquidation fees. Setting your `liquidation_buffer` to 0.0, or using a low `liquidation_buffer` could result in your positions being liquidated. Freqtrade does not track liquidation fees, so liquidations will result in inaccurate profit/loss results for your bot. If you use a low `liquidation_buffer`, it is recommended to use `stoploss_on_exchange` if your exchange supports this.
```

2022-02-11 05:59 UTC, xmatthias commented on freqtrade/exchange/exchange.py
> +            raise OperationalException('Liquidation_buffer must be below 0.99')
This is a setting that's coming from the configuration - so it should be checked right there (adding this to `constants.py` - as mentioned here.

please allow the configuration schema to do the validation (you can set min-max values in the configuration).

2022-02-11 06:47 UTC, samgermain commented on freqtrade/freqtradebot.py
> +        self.liquidation_buffer = float(self.config.get('liquidation_buffer', '0.05'))
I feel like I just like it being inside to exchange.init more than doing a config lookup when executing the trade, but I can move it if you want

2022-02-11 07:05 UTC, xmatthias commented on freqtrade/freqtradebot.py
> +        self.liquidation_buffer = float(self.config.get('liquidation_buffer', '0.05'))
It's a configuration setting - having it not in the config validation will make it crash with "ugly" errors (float conversion failed for example).

e.g. `"liquidation_buffer": "abc",`
I know this is wrong - but it's user input, so we have to validate it.

2022-02-11 19:26 UTC, xmatthias approved these changes
LGTM :+1:

2022-02-11 19:26 UTC, merged

2022-11-15 12:12 UTC, italodamato commented
is it possible to add some logging for this parameter as well as `futures_funding_rate`?

2022-11-15 19:52 UTC, xmatthias commented
`futures_funding_rate` is a fallback that's only used if the exchange doesn't provide a value for that.

If it's there - it's in your config - so best look there.
I don't see us logging this - it'll only be confusing for no good reason
The same is true for liquidation_buffer. It's got a sensible default (5%) that's documented.

The only way to change it is though your config - so if you can read logs - the config is just nearby :)

2022-11-15 23:02 UTC, italodamato commented
I just think it'd be useful to provide some form of feedback to make sure the settings are getting applied correctly.

2022-11-16 05:31 UTC, xmatthias commented
if you think about it - then that's not really true.

You'd have to apply that to all settings (the ones mentioned here are not special, nor really important) - which are around 150 - not considering freqAI.
if you however get a startup log of 150+ messages - you'll not even bother to look through that and try and see if "my setting applied correctly" - so it becomes pointless noise.

The things that are logged are the ones that can be set in either config or strategy.