Slightly reduce verbosity when reload_conf is issued
freqtrade/freqtrade pull request #6473
Opened 2022-02-27 17:54 UTC by mkavinkumar1

old state was compared instead of new

2022-02-27 20:10 UTC, xmatthias commented on freqtrade/worker.py
> +            if state != State.RELOAD_CONFIG:
I'm not sure i understand the point of this (what this tries to accomplish).

What this changes is when this is executed (before/after the reload). 
Please explain which messages / in which scenario you think this makes a difference.

2022-02-28 03:58 UTC, mkavinkumar1 commented
![image](https://user-images.githubusercontent.com/33546454/155921640-c6d48536-e5ea-4e6a-afdf-4127e7352ee9.png)
The second msg is not necessary

2022-02-28 05:49 UTC, xmatthias requested changes
It's incorrect that one of these messages is not needed.

All 3 messages show one particular thing:
1. we received your request to reload the configuration (this is a telegram response - not a state change) - and will not show if you reload via API.
2. we are reloading the configuration (so the bot will now be down for some time)
3. we are now running again.

The mid-state was okish (it changed the wording of the 3rd messages) - but removing this message is not desired, as it hides useful information.

The time between the 2nd and 3rd point can vary greatly depending on the exchange (some exchanges take some time to start up) - so while it might be fast on the configuration you're attempting this - it's not given that that's the case.


![image](https://user-images.githubusercontent.com/5024695/155931015-9a473346-4e4f-47e4-874f-04acf9616310.png)

You're now hiding the fact of what the new state is. It could be running (default config) - but it could also be stopped (if startup-state is stopped in the configuration).

2022-02-28 06:09 UTC, mkavinkumar1 commented
> You're now also hiding the fact of what the new state is. It could be running (default config) - but it could also be stopped (if startup-state is stopped in the configuration).

the new state is already ignored.

2022-02-28 06:10 UTC, xmatthias commented
> the new state is already ignored.

Which is why i said - the "middle ground" you had was better :)

2022-02-28 10:32 UTC, mkavinkumar1 commented
> The time between the 2nd and 3rd point can vary greatly depending on the exchange

But the time between 1st and 2nd is instant only. Will the 2nd one fail after 1st?

2022-02-28 12:35 UTC, xmatthias commented
> But the time between 1st and 2nd is instant only.

No it's not - it'll depend on the exchange and configuration / setup. 

As mentioned above - the wording can change (which was the first commit) - but the remainder is not desired (so there will be 2 messages - one for "reloading" (start) - and one for "reloaded/running" (end)) - also when reloading via API (which will remove the very first message, which is a response).

The current instance moves further away from that - and is therefore an unwanted change.

2022-02-28 12:59 UTC, closed without merging