Display the signal candle analyzed in telegram.
freqtrade/freqtrade pull request #6916
Opened 2022-05-31 20:03 UTC by SurferAdmin

All the tests completed and test result files are attached. Thank you all!

## Summary

Show the actual candle analyzed in telegram.

Solve the issue: # 6915

Update freqtradebot.py to get and send the candle analyzed to create the entry or exit signal
Update telegram.py to send the candle analyzed to telegram

## What's new?

The PR displays the analyzed candle facilitating ease of discovery in the Binance portal the exact candle. This helps visually verify and provide ideas of improvement to the strategy. 

<img width="1002" alt="Screen Shot 2022-05-31 at 3 13 22 PM" src="https://user-images.githubusercontent.com/64109384/171274934-eac42dcb-72b4-4787-bf98-b3182c04b902.png">
<img width="947" alt="Screen Shot 2022-05-31 at 3 14 02 PM" src="https://user-images.githubusercontent.com/64109384/171274940-8435dadd-5124-41ba-96c4-5dde7962e697.png">
[result_flake8.txt](https://github.com/freqtrade/freqtrade/files/8809024/result_flake8.txt)
[result_isort.txt](https://github.com/freqtrade/freqtrade/files/8809025/result_isort.txt)
[result_pytest.txt](https://github.com/freqtrade/freqtrade/files/8809026/result_pytest.txt)
[result_type-hints.txt](https://github.com/freqtrade/freqtrade/files/8809027/result_type-hints.txt)

2022-05-31 20:23 UTC, eSeR1805 commented
Maybe add a config toggle in the telegram section for people to choose if they want this extra reporting or not?
Feels like this is relevant for your usecases but for others(like me) it might be just clutter.

2022-05-31 20:43 UTC, FlockrushAdmin commented
> Maybe add a config toggle in the telegram section for people to choose if they want this extra reporting or not? Feels like this is relevant for your usecases but for others(like me) it might be just extra clutter.

Will do. Thank you!!!

2022-06-01 04:24 UTC, xmatthias commented
i'm ... not entirely sure how to approach this yet.

i don't really like the formatting (it's just a json blob ...) ... (but wait and read on)...

i can see it can provide benefits in some areas - but for other usecases, i fear it'll not go far enough.

People will want to see 'their' indicators, too - so maybe make that 'switch' a bit more dynamic - like 
'off' - default
'ohlcv' -> what you show now
'full' -> unfiltered candle

2022-06-01 06:17 UTC, SurferAdmin commented
> 



> i'm ... not entirely sure how to approach this yet.
> 
> i don't really like the formatting (it's just a json blob ...) which especially on a phone, will look quite bad as it will wrap 'wherever' ... (but wait and read on)...
> 
> i can see it can provide benefits in some areas - but for other use cases, i fear it'll not go far enough.
> 
> People will want to see 'their' indicators, too - so maybe make that 'switch' a bit more dynamic - like 'off' - default 'ohlcv' -> what you show now 'full' -> unfiltered candle

Agreed better formatting and a more detailed raw option can be easier to digest and useful. 

I do raw csv output for agi model refinement tasks, but had struggled for an easier way for a chart peek without opening those files.  Ideally if binance had and an api hook for their charts. 

I will add a more detailed version with the suggested test coverage. 

Have an awesome week!!!

2022-06-21 18:12 UTC, xmatthias requested changes
Please make sure to only include data you want - `git commit -a` should only be used once you've confirmed that the changes include what you intend to contribute.

2022-06-21 18:12 UTC, xmatthias commented on freqtrade/templates/strategy_analysis_example.ipynb
> +     "evalue": "Directory `/Users/surfer/Software/MMM/develop/freqtrade/freqtrade/templates/user_data` does not exist. Please use `freqtrade create-userdir` to create a user directory",
Please make sure to only commit what you'd like to have included.
a jupyter notebook that's been executed is clearly not among these.

2022-06-21 18:12 UTC, xmatthias commented on .gitignore
> +doc/doc-script.js
I don't think these files make sense to include in a gitignore file.

they're not part of the repository - and excluding .gitignore is kinda dangerous.

2022-07-11 13:59 UTC, merged

2022-07-11 13:59 UTC, xmatthias commented
As this branch saw no progress, and pushing to this branch is disabled (most likely implicitly, as the PR was done from your develop branch) - i've added the necessary changes and merged the changes directly.

It's now "optin" - so people have to explicitly enable this - as i think it'll clutter people's results without much reason (this is often non-necessary information).