Fix constant PCA
freqtrade/freqtrade pull request #7593
Opened 2022-10-15 21:37 UTC by th0rntwig

## Summary

Bug fix for KeyError() trying to remove constant features with PCA enabled.

## Quick changelog

Constant features are removed as they do not contribute to the model. When PCA is enabled, the constant features that were removed no longer matches the df keys and throws an error. This PR disables the removal of constant features if PCA is enabled, as PCA will "remove" them by itself (it only keeps components influencing the variance of the data and a constant feature has little influence).

2022-10-16 18:35 UTC, robcaulk requested changes

2022-10-16 18:35 UTC, robcaulk commented on freqtrade/freqai/data_kitchen.py
> +            if not ft_params.get(
I think we still want to check for constant columns when we filter for training data (even when `principal_component_analysis` is true). This occurs *before* PCA, and we want to feed the non constant cols into PCA. 

Correct me if I am missing something.

2022-10-18 10:25 UTC, th0rntwig commented on freqtrade/freqai/data_kitchen.py
> +            if not ft_params.get(
The idea with this was that since PCA basically looks for variance in the data, a constant feature would be "automatically deselected" and we wouldn't need to find it and remove it before, reducing computational power (very slightly but still). But depending on future additions to the code, making this check agnostic to manipulations of the feature labels would indeed be the better way of doing it. I'll make the required changes!

2022-10-23 14:30 UTC, th0rntwig commented
I changed the storage location for the constant column labels to `datakitchen.data()`. This caused the `test_normalize_data` to throw an error as it checked for the length of `datakitchen.data()`. That test now checks for entries `_max` and `_min` (substrings of the entries added in `normalize_data`) in the dict keys instead of its length.

2022-10-23 18:56 UTC, robcaulk approved these changes
LGTM

2022-10-23 18:56 UTC, robcaulk commented on freqtrade/freqai/data_kitchen.py
> +            if len(self.constant_features_list):
I don't see how this will ever be anything besides an empty list. 

We train in a separate thread to the prediction (inferencing). You are attaching `self.constant_feature_list` to the temporary `dk` object. If you want information to persist from training to inference, you need to use `self.data` because `dk.data` is loaded in to the data kitchen eachtime a temporary data kitchen is created for a new coin.

2022-10-24 06:33 UTC, merged