Fix dependencies & tests to run on Windows
freqtrade/freqtrade pull request #8231
Opened 2023-02-26 12:22 UTC by asuiu

## Summary
Fix dependencies and tests to run on Windows.

Currently some of the dependencies are incompatible with Windows, as well as some tests fail to run on Windows and this PR fixes to make all tests pass by ignoring those incompatible, and not installing incompatible packages on Windows.

## Quick changelog

- fix `requirements-freqai-rl.txt` to not install on Win platform incompatible packages;
- fix tests to skip running incompatible tests on Win platform;

## What's new?

No new features/functionalities.

2023-02-26 13:10 UTC, xmatthias requested changes
I disagree with basically every line in this.

it's fixing something that's related to your setup (not to windows specifically) - and skipping a whole segment of tests for no good reason (again - your specific setup).

The health part is very similar - it's environment specific (and pretty sure it's affecting you) - but skipping that test is the wrong fix.

2023-02-26 13:10 UTC, xmatthias commented on requirements-freqai-rl.txt
> +stable-baselines3==1.7.0; sys_platform != "win32"
I disagree with this.

CI clearly shows that both installation, as well as tests are running fine on windows.
It's therefore most likely related to your specific setup.

2023-02-26 13:10 UTC, xmatthias commented on tests/freqai/test_freqai_interface.py
> +if sys.platform.startswith("win"):
We will not be skipping the whole freqAI tests on windows.
that's both unnecessary, as well as danerous.

best fix your setup instead.

2023-02-26 13:10 UTC, xmatthias commented on tests/rpc/test_rpc_apiserver.py
>      ftbot, client = botclient
The actual problem is not windows (look at CI for this).

I've seen this before though - and it's if you're running a test (on windows) on a negative timezone (i suspect in rare edgecases, it can also happen in live mode in these circumstance).

I'm happy to get a PR fixing that particular issue properly - but skipping this test is not the fix.

2023-02-26 17:09 UTC, asuiu commented
@xmatthias 
Thank you for taking time to review. I apologize for the confusion and for overlooking the fact that there is already a working Windows Continuous Integration pipeline. In this context, as you mentioned, there is no point in skipping those tests since the pipeline works. It looks that is was something wrong with my set-up, software we use is not perfect. With the presence of passing Windows CI pipeline - this PR just doesn't make any sense.

Once again, I apologize for any inconvenience or confusion that my PR may have caused, and I appreciate your willingness to review and explain the issue.

I close this PR.

2023-02-26 17:09 UTC, closed without merging

2023-02-27 05:30 UTC, xmatthias commented
As mentioned the "health" test is a different topic - which i struggle to recreate as it requires windows (which i don't use) on a negative timezone offset (basically US) - which i'm not in.

The fix for THAT would be great - it'll be in `rpc.py -> _health()` - where `astimezone()` is creating the rpoblem - and might need slightly different handling for `0` values (i traced it this far last time i looked at this)

2023-02-27 09:44 UTC, asuiu commented
> As mentioned the "health" test is a different topic - which i struggle to recreate as it requires windows (which i don't use) on a negative timezone offset (basically US) - which i'm not in.
> 
> The fix for THAT would be great - it'll be in `rpc.py -> _health()` - where `astimezone()` is creating the rpoblem - and might need slightly different handling for `0` values (i traced it this far last time i looked at this)

@xmatthias 
I have created a separate issue for this, for easier tracking: https://github.com/freqtrade/freqtrade/issues/8244